[package]
name = "anaso_sdk"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "SDK for the Ana.so API"

[workspace]
members = ["anaso_api_models"]
resolver = "2"

[dependencies]
